using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using AutoRepo.Models;

namespace AutoRepo.Emitters;

public static class CombinedEmitter
{
    public static string Emit(RepositoryModel repo)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.Logging;");

        var baseNamespace = repo.Namespace.EndsWith(".Abstractions")
            ? repo.Namespace.Substring(0, repo.Namespace.Length - ".Abstractions".Length)
            : repo.Namespace;
        sb.AppendLine($"using {baseNamespace}.Repositories;");
        sb.AppendLine($"using {baseNamespace}.Entities;");
        sb.AppendLine();
        sb.AppendLine($"namespace {repo.Namespace}.Generated;");
        sb.AppendLine();

        var concreteRepoName = repo.Name;

        sb.AppendLine($"public class Combined{repo.Name} : {repo.InterfaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {concreteRepoName} _local;");
        sb.AppendLine($"    private readonly IApi{repo.Name} _api;");
        sb.AppendLine($"    private readonly ILogger<Combined{repo.Name}> _logger;");
        sb.AppendLine();

        EmitConstructor(sb, repo, concreteRepoName);
        EmitSafeApiCallHelper(sb);

        foreach (var method in repo.Methods)
        {
            EmitMethod(sb, repo, method);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitConstructor(StringBuilder sb, RepositoryModel repo, string concreteRepoName)
    {
        sb.AppendLine($"    public Combined{repo.Name}(");
        sb.AppendLine($"        {concreteRepoName} local,");
        sb.AppendLine($"        IApi{repo.Name} api,");
        sb.AppendLine($"        ILogger<Combined{repo.Name}> logger)");
        sb.AppendLine("    {");
        sb.AppendLine("        _local = local;");
        sb.AppendLine("        _api = api;");
        sb.AppendLine("        _logger = logger;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitSafeApiCallHelper(StringBuilder sb)
    {
        sb.AppendLine("    private async Task<T?> SafeApiCallAsync<T>(Func<Task<T?>> apiCall) where T : class");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            return await apiCall();");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            _logger.LogWarning(ex, \"API call failed, continuing with local data only\");");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    private async Task<T?> SafeApiCallCollectionAsync<T>(Func<Task<T>> apiCall) where T : class");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            return await apiCall();");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            _logger.LogWarning(ex, \"API call failed, continuing with local data only\");");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitMethod(StringBuilder sb, RepositoryModel repo, MethodModel method)
    {
        var signature = BuildMethodSignature(method);
        var strategy = DetermineStrategy(method);

        sb.AppendLine($"    public async {signature}");
        sb.AppendLine("    {");

        switch (strategy)
        {
            case CombinedStrategy.MergeCollections:
                EmitMergeCollectionsBody(sb, repo, method);
                break;
            case CombinedStrategy.MergeSingleItem:
                EmitMergeSingleItemBody(sb, repo, method);
                break;
            case CombinedStrategy.LocalOnly:
                EmitLocalOnlyBody(sb, method);
                break;
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string BuildMethodSignature(MethodModel method)
    {
        var parameters = method.Parameters.Select(p =>
        {
            var defaultValue = "";
            if (p.HasDefaultValue)
            {
                if (p.IsCancellationToken)
                    defaultValue = " = default";
                else if (p.DefaultValue is null)
                    defaultValue = " = null";
                else if (p.DefaultValue is bool b)
                    defaultValue = b ? " = true" : " = false";
                else if (p.DefaultValue is string s)
                    defaultValue = $" = \"{s}\"";
                else
                    defaultValue = $" = {p.DefaultValue}";
            }

            return $"{p.Type} {p.Name}{defaultValue}";
        });

        return $"{method.ReturnType} {method.Name}({string.Join(", ", parameters)})";
    }

    private static CombinedStrategy DetermineStrategy(MethodModel method)
    {
        if (method.Name.StartsWith("Upsert") ||
            method.Name.StartsWith("Create") ||
            method.Name.StartsWith("Update") ||
            method.Name.StartsWith("Delete") ||
            method.Name.StartsWith("Remove") ||
            method.Name.StartsWith("Add"))
        {
            return CombinedStrategy.LocalOnly;
        }

        if (method.Name.StartsWith("GetStored") || method.Name.StartsWith("GetLibrary"))
        {
            return CombinedStrategy.LocalOnly;
        }

        if (!method.HasSource && method.InnerReturnType != "void")
        {
            return CombinedStrategy.LocalOnly;
        }

        if (method.ReturnsCollection)
        {
            return CombinedStrategy.MergeCollections;
        }

        return CombinedStrategy.MergeSingleItem;
    }

    private static void EmitMergeCollectionsBody(StringBuilder sb, RepositoryModel repo, MethodModel method)
    {
        var callArgs = BuildCallArgs(method);
        var elementType = ExtractCollectionElementType(method.InnerReturnType);

        sb.AppendLine($"        // Query both sources in parallel");
        sb.AppendLine($"        var localTask = _local.{method.Name}({callArgs});");
        sb.AppendLine($"        var apiTask = SafeApiCallCollectionAsync(() => _api.{method.Name}({callArgs}));");
        sb.AppendLine();
        sb.AppendLine($"        var localResults = await localTask;");
        sb.AppendLine($"        var apiResults = await apiTask;");
        sb.AppendLine();
        sb.AppendLine($"        // Merge by ID, prefer local for duplicates");
        sb.AppendLine($"        var combined = new Dictionary<{repo.IdType}, {elementType}>();");
        sb.AppendLine();
        sb.AppendLine($"        if (apiResults != null)");
        sb.AppendLine("        {");
        sb.AppendLine($"            foreach (var item in apiResults)");
        sb.AppendLine("            {");
        if (method.HasSource)
            sb.AppendLine($"                item.Source = DataSource.Remote;");
        sb.AppendLine($"                combined[item.Id] = item;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        foreach (var item in localResults)");
        sb.AppendLine("        {");
        if (method.HasSource)
        {
            sb.AppendLine($"            if (combined.ContainsKey(item.Id))");
            sb.AppendLine("            {");
            sb.AppendLine($"                item.Source = DataSource.Both;");
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            sb.AppendLine($"                item.Source = DataSource.Local;");
            sb.AppendLine("            }");
        }
        sb.AppendLine($"            combined[item.Id] = item;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        _logger.LogDebug(\"Combined {{LocalCount}} local + {{RemoteCount}} remote = {{TotalCount}} items\",");
        sb.AppendLine($"            localResults.Count, apiResults?.Count ?? 0, combined.Count);");
        sb.AppendLine();
        sb.AppendLine($"        return combined.Values.ToList();");
    }

    private static void EmitMergeSingleItemBody(StringBuilder sb, RepositoryModel repo, MethodModel method)
    {
        var callArgs = BuildCallArgs(method);
        var idParam = method.Parameters.FirstOrDefault(p => p.IsRouteParameter);
        var idLogValue = idParam != null ? idParam.Name : "request";

        sb.AppendLine($"        // Check both sources in parallel");
        sb.AppendLine($"        var localTask = _local.{method.Name}({callArgs});");
        sb.AppendLine($"        var apiTask = SafeApiCallAsync(() => _api.{method.Name}({callArgs}));");
        sb.AppendLine();
        sb.AppendLine($"        var localResult = await localTask;");
        sb.AppendLine($"        var apiResult = await apiTask;");
        sb.AppendLine();
        sb.AppendLine($"        if (localResult != null && apiResult != null)");
        sb.AppendLine("        {");
        if (method.HasSource)
            sb.AppendLine($"            localResult.Source = DataSource.Both;");
        sb.AppendLine($"            _logger.LogDebug(\"{{Id}} found in both local and remote\", {idLogValue});");
        sb.AppendLine($"            return localResult;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        if (localResult != null)");
        sb.AppendLine("        {");
        if (method.HasSource)
            sb.AppendLine($"            localResult.Source = DataSource.Local;");
        sb.AppendLine($"            _logger.LogDebug(\"{{Id}} found in local only\", {idLogValue});");
        sb.AppendLine($"            return localResult;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        if (apiResult != null)");
        sb.AppendLine("        {");
        if (method.HasSource)
            sb.AppendLine($"            apiResult.Source = DataSource.Remote;");
        sb.AppendLine($"            _logger.LogDebug(\"{{Id}} found in remote only\", {idLogValue});");
        sb.AppendLine($"            return apiResult;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        _logger.LogDebug(\"{{Id}} not found in either source\", {idLogValue});");
        sb.AppendLine($"        return null;");
    }

    private static void EmitLocalOnlyBody(StringBuilder sb, MethodModel method)
    {
        var callArgs = BuildCallArgs(method);
        var returnsVoid = method.InnerReturnType == "void" ||
                          method.ReturnType == "System.Threading.Tasks.Task" ||
                          method.ReturnType == "Task";

        sb.AppendLine($"        // Mutations go to local only");
        if (returnsVoid)
        {
            sb.AppendLine($"        await _local.{method.Name}({callArgs});");
        }
        else
        {
            sb.AppendLine($"        return await _local.{method.Name}({callArgs});");
        }
    }

    private static string BuildCallArgs(MethodModel method)
    {
        return string.Join(", ", method.Parameters.Select(p => p.Name));
    }

    private static string ExtractCollectionElementType(string collectionType)
    {
        var startIndex = collectionType.IndexOf('<');
        var endIndex = collectionType.LastIndexOf('>');

        if (startIndex >= 0 && endIndex > startIndex)
        {
            return collectionType.Substring(startIndex + 1, endIndex - startIndex - 1);
        }

        return collectionType;
    }

    private enum CombinedStrategy
    {
        MergeCollections,
        MergeSingleItem,
        LocalOnly
    }
}
