using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using AutoRepo.Models;

namespace AutoRepo.Emitters;

public static class FallbackEmitter
{
    public static string Emit(RepositoryModel repo)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.Logging;");

        var baseNamespace = repo.Namespace.EndsWith(".Abstractions")
            ? repo.Namespace.Substring(0, repo.Namespace.Length - ".Abstractions".Length)
            : repo.Namespace;
        sb.AppendLine($"using {baseNamespace}.Repositories;");
        sb.AppendLine($"using {baseNamespace}.Entities;");
        sb.AppendLine();
        sb.AppendLine($"namespace {repo.Namespace}.Generated;");
        sb.AppendLine();

        var concreteRepoName = repo.Name;

        sb.AppendLine($"public class Fallback{repo.Name} : {repo.InterfaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {concreteRepoName} _local;");
        sb.AppendLine($"    private readonly IApi{repo.Name} _api;");
        sb.AppendLine($"    private readonly ILogger<Fallback{repo.Name}> _logger;");
        sb.AppendLine();

        EmitConstructor(sb, repo, concreteRepoName);

        foreach (var method in repo.Methods)
        {
            EmitMethod(sb, repo, method);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitConstructor(StringBuilder sb, RepositoryModel repo, string concreteRepoName)
    {
        sb.AppendLine($"    public Fallback{repo.Name}(");
        sb.AppendLine($"        {concreteRepoName} local,");
        sb.AppendLine($"        IApi{repo.Name} api,");
        sb.AppendLine($"        ILogger<Fallback{repo.Name}> logger)");
        sb.AppendLine("    {");
        sb.AppendLine("        _local = local;");
        sb.AppendLine("        _api = api;");
        sb.AppendLine("        _logger = logger;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitMethod(StringBuilder sb, RepositoryModel repo, MethodModel method)
    {
        var signature = BuildMethodSignature(method);
        var strategy = DetermineStrategy(method);

        sb.AppendLine($"    public async {signature}");
        sb.AppendLine("    {");

        switch (strategy)
        {
            case FallbackStrategy.LocalFirst:
                EmitLocalFirstBody(sb, repo, method);
                break;
            case FallbackStrategy.ApiFirst:
                EmitApiFirstBody(sb, repo, method);
                break;
            case FallbackStrategy.LocalOnly:
                EmitLocalOnlyBody(sb, method);
                break;
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string BuildMethodSignature(MethodModel method)
    {
        var parameters = method.Parameters.Select(p =>
        {
            var defaultValue = "";
            if (p.HasDefaultValue)
            {
                if (p.IsCancellationToken)
                    defaultValue = " = default";
                else if (p.DefaultValue is null)
                    defaultValue = " = null";
                else if (p.DefaultValue is bool b)
                    defaultValue = b ? " = true" : " = false";
                else if (p.DefaultValue is string s)
                    defaultValue = $" = \"{s}\"";
                else
                    defaultValue = $" = {p.DefaultValue}";
            }

            return $"{p.Type} {p.Name}{defaultValue}";
        });

        return $"{method.ReturnType} {method.Name}({string.Join(", ", parameters)})";
    }

    private static FallbackStrategy DetermineStrategy(MethodModel method)
    {
        if (method.Name.StartsWith("Upsert") ||
            method.Name.StartsWith("Create") ||
            method.Name.StartsWith("Update") ||
            method.Name.StartsWith("Delete") ||
            method.Name.StartsWith("Remove") ||
            method.Name.StartsWith("Add"))
        {
            return FallbackStrategy.LocalOnly;
        }

        if (!method.HasSource && method.InnerReturnType != "void")
        {
            return FallbackStrategy.LocalOnly;
        }

        if (method.ReturnsCollection)
        {
            return FallbackStrategy.ApiFirst;
        }

        return FallbackStrategy.LocalFirst;
    }

    private static void EmitLocalFirstBody(StringBuilder sb, RepositoryModel repo, MethodModel method)
    {
        var callArgs = BuildCallArgs(method);
        var idParam = method.Parameters.FirstOrDefault(p => p.IsRouteParameter);
        var idLogValue = idParam != null ? idParam.Name : "request";

        sb.AppendLine($"        // Try local database first");
        sb.AppendLine($"        var result = await _local.{method.Name}({callArgs});");
        sb.AppendLine($"        if (result is not null)");
        sb.AppendLine("        {");
        if (method.HasSource)
            sb.AppendLine($"            result.Source = DataSource.Local;");
        sb.AppendLine($"            _logger.LogDebug(\"Found {{Id}} in local database\", {idLogValue});");
        sb.AppendLine($"            return result;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        // Fallback to API");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            _logger.LogDebug(\"{{Id}} not found locally, trying API\", {idLogValue});");
        sb.AppendLine($"            var apiResult = await _api.{method.Name}({callArgs});");
        if (method.HasSource)
        {
            sb.AppendLine($"            if (apiResult is not null)");
            sb.AppendLine("            {");
            sb.AppendLine($"                apiResult.Source = DataSource.Remote;");
            sb.AppendLine("            }");
        }
        sb.AppendLine($"            return apiResult;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine($"            _logger.LogWarning(ex, \"Failed to fetch {{Id}} from API\", {idLogValue});");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
    }

    private static void EmitApiFirstBody(StringBuilder sb, RepositoryModel repo, MethodModel method)
    {
        var callArgs = BuildCallArgs(method);

        sb.AppendLine($"        // Try API first (browsing catalog)");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            var result = await _api.{method.Name}({callArgs});");
        if (method.HasSource)
        {
            sb.AppendLine($"            foreach (var item in result)");
            sb.AppendLine("            {");
            sb.AppendLine($"                item.Source = DataSource.Remote;");
            sb.AppendLine("            }");
        }
        sb.AppendLine($"            return result;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine($"            _logger.LogWarning(ex, \"Failed to fetch from API, using local\");");
        sb.AppendLine($"            var localResult = await _local.{method.Name}({callArgs});");
        if (method.HasSource)
        {
            sb.AppendLine($"            foreach (var item in localResult)");
            sb.AppendLine("            {");
            sb.AppendLine($"                item.Source = DataSource.Local;");
            sb.AppendLine("            }");
        }
        sb.AppendLine($"            return localResult;");
        sb.AppendLine("        }");
    }

    private static void EmitLocalOnlyBody(StringBuilder sb, MethodModel method)
    {
        var callArgs = BuildCallArgs(method);
        var returnsVoid = method.InnerReturnType == "void" ||
                          method.ReturnType == "System.Threading.Tasks.Task" ||
                          method.ReturnType == "Task";

        sb.AppendLine($"        // Mutations go to local only");
        if (returnsVoid)
        {
            sb.AppendLine($"        await _local.{method.Name}({callArgs});");
        }
        else
        {
            sb.AppendLine($"        return await _local.{method.Name}({callArgs});");
        }
    }

    private static string BuildCallArgs(MethodModel method)
    {
        return string.Join(", ", method.Parameters.Select(p => p.Name));
    }

    private enum FallbackStrategy
    {
        LocalFirst,
        ApiFirst,
        LocalOnly
    }
}
