using System.Collections.Generic;
using System.Linq;
using System.Text;
using AutoRepo.Models;

namespace AutoRepo.Emitters;

public static class HttpClientEmitter
{
    public static string Emit(RepositoryModel repo)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {repo.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"public class Api{repo.Name}Client : IApi{repo.Name}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly HttpClient _http;");

        // Use custom JsonOptionsType if provided, otherwise use sensible defaults
        if (!string.IsNullOrEmpty(repo.JsonOptionsType))
        {
            sb.AppendLine($"    private static readonly JsonSerializerOptions _jsonOptions = {repo.JsonOptionsType}.Default;");
        }
        else
        {
            sb.AppendLine("    private static readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions");
            sb.AppendLine("    {");
            sb.AppendLine("        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,");
            sb.AppendLine("        PropertyNameCaseInsensitive = true");
            sb.AppendLine("    };");
        }

        sb.AppendLine();
        sb.AppendLine($"    public Api{repo.Name}Client(HttpClient http)");
        sb.AppendLine("    {");
        sb.AppendLine("        _http = http;");
        sb.AppendLine("    }");

        foreach (var method in repo.Methods)
        {
            sb.AppendLine();
            EmitMethod(sb, repo, method);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, RepositoryModel repo, MethodModel method)
    {
        var parameters = FormatParameters(method);
        var route = BuildRoute(repo.RoutePrefix, method);

        sb.AppendLine($"    public async {method.ReturnType} {method.Name}({parameters})");
        sb.AppendLine("    {");

        EmitUrlConstruction(sb, route, method);
        EmitHttpCall(sb, method);

        sb.AppendLine("    }");
    }

    private static void EmitUrlConstruction(StringBuilder sb, string route, MethodModel method)
    {
        sb.AppendLine($"        var url = $\"{route}\";");

        var queryParams = method.Parameters
            .Where(p => p.IsQueryParameter && !p.IsCancellationToken)
            .ToList();

        if (queryParams.Count > 0)
        {
            sb.AppendLine("        var queryParts = new List<string>();");

            foreach (var param in queryParams)
            {
                if (param.Type.EndsWith("?"))
                {
                    sb.AppendLine($"        if ({param.Name} != null) queryParts.Add($\"{param.Name}={{{param.Name}}}\");");
                }
                else
                {
                    sb.AppendLine($"        queryParts.Add($\"{param.Name}={{{param.Name}}}\");");
                }
            }

            sb.AppendLine("        if (queryParts.Count > 0) url += \"?\" + string.Join(\"&\", queryParts);");
        }
    }

    private static void EmitHttpCall(StringBuilder sb, MethodModel method)
    {
        var ctParam = method.Parameters.FirstOrDefault(p => p.IsCancellationToken);
        var ctArg = ctParam != null ? ctParam.Name : "default";
        var bodyParam = method.Parameters.FirstOrDefault(p => p.IsBodyParameter);
        var innerType = method.InnerReturnType;

        switch (method.HttpMethod)
        {
            case HttpMethod.Get:
                if (method.ReturnsCollection)
                {
                    var elementType = ExtractCollectionElementType(innerType);
                    sb.AppendLine($"        var response = await _http.GetFromJsonAsync<List<{elementType}>>(url, _jsonOptions, {ctArg});");
                    sb.AppendLine($"        return (IReadOnlyList<{elementType}>)(response ?? new List<{elementType}>());");
                }
                else if (innerType == "void")
                {
                    sb.AppendLine($"        await _http.GetAsync(url, {ctArg});");
                }
                else
                {
                    sb.AppendLine($"        return await _http.GetFromJsonAsync<{innerType}>(url, _jsonOptions, {ctArg});");
                }
                break;

            case HttpMethod.Post:
                if (bodyParam != null)
                {
                    if (innerType == "void")
                    {
                        sb.AppendLine($"        var response = await _http.PostAsJsonAsync(url, {bodyParam.Name}, _jsonOptions, {ctArg});");
                        sb.AppendLine("        response.EnsureSuccessStatusCode();");
                    }
                    else
                    {
                        sb.AppendLine($"        var response = await _http.PostAsJsonAsync(url, {bodyParam.Name}, _jsonOptions, {ctArg});");
                        sb.AppendLine("        response.EnsureSuccessStatusCode();");
                        sb.AppendLine($"        return await response.Content.ReadFromJsonAsync<{innerType}>(_jsonOptions, {ctArg});");
                    }
                }
                else
                {
                    if (innerType == "void")
                    {
                        sb.AppendLine($"        var response = await _http.PostAsync(url, null, {ctArg});");
                        sb.AppendLine("        response.EnsureSuccessStatusCode();");
                    }
                    else
                    {
                        sb.AppendLine($"        var response = await _http.PostAsync(url, null, {ctArg});");
                        sb.AppendLine("        response.EnsureSuccessStatusCode();");
                        sb.AppendLine($"        return await response.Content.ReadFromJsonAsync<{innerType}>(_jsonOptions, {ctArg});");
                    }
                }
                break;

            case HttpMethod.Put:
                if (bodyParam != null)
                {
                    if (innerType == "void")
                    {
                        sb.AppendLine($"        var response = await _http.PutAsJsonAsync(url, {bodyParam.Name}, _jsonOptions, {ctArg});");
                        sb.AppendLine("        response.EnsureSuccessStatusCode();");
                    }
                    else
                    {
                        sb.AppendLine($"        var response = await _http.PutAsJsonAsync(url, {bodyParam.Name}, _jsonOptions, {ctArg});");
                        sb.AppendLine("        response.EnsureSuccessStatusCode();");
                        sb.AppendLine($"        return await response.Content.ReadFromJsonAsync<{innerType}>(_jsonOptions, {ctArg});");
                    }
                }
                else
                {
                    sb.AppendLine($"        var response = await _http.PutAsync(url, null, {ctArg});");
                    sb.AppendLine("        response.EnsureSuccessStatusCode();");
                }
                break;

            case HttpMethod.Delete:
                if (innerType == "void")
                {
                    sb.AppendLine($"        var response = await _http.DeleteAsync(url, {ctArg});");
                    sb.AppendLine("        response.EnsureSuccessStatusCode();");
                }
                else
                {
                    sb.AppendLine($"        var response = await _http.DeleteAsync(url, {ctArg});");
                    sb.AppendLine("        response.EnsureSuccessStatusCode();");
                    sb.AppendLine($"        return await response.Content.ReadFromJsonAsync<{innerType}>(_jsonOptions, {ctArg});");
                }
                break;
        }
    }

    private static string BuildRoute(string routePrefix, MethodModel method)
    {
        var parts = new List<string> { routePrefix.TrimEnd('/') };

        foreach (var param in method.Parameters.Where(p => p.IsRouteParameter))
        {
            parts.Add($"{{{param.Name}}}");
        }

        if (method.Name.StartsWith("Search"))
        {
            if (method.Parameters.Any(p => p.IsRouteParameter))
                parts.Insert(1, "search");
            else
                parts.Add("search");
        }

        return string.Join("/", parts);
    }

    private static string FormatParameters(MethodModel method)
    {
        var parts = new List<string>();

        foreach (var param in method.Parameters)
        {
            var defaultValue = GetDefaultValueString(param);
            parts.Add($"{param.Type} {param.Name}{defaultValue}");
        }

        return string.Join(", ", parts);
    }

    private static string GetDefaultValueString(ParameterModel param)
    {
        if (!param.HasDefaultValue)
            return string.Empty;

        if (param.IsCancellationToken)
            return " = default";

        if (param.DefaultValue is null)
            return " = null";

        if (param.DefaultValue is bool b)
            return b ? " = true" : " = false";

        if (param.DefaultValue is string s)
            return $" = \"{s}\"";

        return $" = {param.DefaultValue}";
    }

    private static string ExtractCollectionElementType(string typeName)
    {
        var start = typeName.IndexOf('<');
        var end = typeName.LastIndexOf('>');
        if (start >= 0 && end > start)
        {
            return typeName.Substring(start + 1, end - start - 1);
        }
        return typeName;
    }
}
