using System.Collections.Generic;
using System.Linq;
using System.Text;
using AutoRepo.Models;

namespace AutoRepo.Emitters;

public static class RefitEmitter
{
    public static string Emit(RepositoryModel repo)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Refit;");
        sb.AppendLine();
        sb.AppendLine($"namespace {repo.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"public interface IApi{repo.Name}");
        sb.AppendLine("{");

        foreach (var method in repo.Methods)
        {
            EmitMethod(sb, repo, method);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, RepositoryModel repo, MethodModel method)
    {
        var route = BuildRoute(repo.RoutePrefix, method);
        var httpAttribute = GetHttpAttribute(method, route);
        var parameters = FormatParameters(method);

        sb.AppendLine($"    {httpAttribute}");
        sb.AppendLine($"    {method.ReturnType} {method.Name}({parameters});");
        sb.AppendLine();
    }

    private static string GetHttpAttribute(MethodModel method, string route)
    {
        return method.HttpMethod switch
        {
            HttpMethod.Get => $"[Get(\"{route}\")]",
            HttpMethod.Post => $"[Post(\"{route}\")]",
            HttpMethod.Put => $"[Put(\"{route}\")]",
            HttpMethod.Delete => $"[Delete(\"{route}\")]",
            _ => $"[Get(\"{route}\")]"
        };
    }

    private static string BuildRoute(string routePrefix, MethodModel method)
    {
        var parts = new List<string> { routePrefix.TrimEnd('/') };

        foreach (var param in method.Parameters.Where(p => p.IsRouteParameter))
        {
            parts.Add($"{{{param.Name}}}");
        }

        if (method.Name.StartsWith("Search"))
        {
            if (method.Parameters.Any(p => p.IsRouteParameter))
                parts.Insert(1, "search");
            else
                parts.Add("search");
        }

        return string.Join("/", parts);
    }

    private static string FormatParameters(MethodModel method)
    {
        var parts = new List<string>();

        foreach (var param in method.Parameters)
        {
            var attribute = GetParameterAttribute(param);
            var defaultValue = GetDefaultValueString(param);
            parts.Add($"{attribute}{param.Type} {param.Name}{defaultValue}");
        }

        return string.Join(", ", parts);
    }

    private static string GetParameterAttribute(ParameterModel param)
    {
        if (param.IsRouteParameter)
            return "";

        if (param.IsBodyParameter)
            return "[Body] ";

        if (param.IsQueryParameter)
            return "[Query] ";

        return "";
    }

    private static string GetDefaultValueString(ParameterModel param)
    {
        if (!param.HasDefaultValue)
            return string.Empty;

        if (param.IsCancellationToken)
            return " = default";

        if (param.DefaultValue is null)
            return " = null";

        if (param.DefaultValue is bool b)
            return b ? " = true" : " = false";

        if (param.DefaultValue is string s)
            return $" = \"{s}\"";

        return $" = {param.DefaultValue}";
    }
}
