using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using AutoRepo.Emitters;
using AutoRepo.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AutoRepo;

[Generator]
public class RepositoryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Emit the [GenerateApi] attribute so consumers don't need to define it
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("GenerateApiAttribute.g.cs", @"// <auto-generated/>
#nullable enable

namespace AutoRepo;

/// <summary>
/// Marks a repository interface for API code generation.
/// The source generator will create:
/// - IApi{Name} (Refit interface for client-side API calls)
/// - Api{Name}Client (HttpClient-based implementation)
/// - Fallback{Name} (local-first wrapper with API fallback)
/// - Combined{Name} (merged wrapper querying both sources)
/// </summary>
[System.AttributeUsage(System.AttributeTargets.Interface)]
public class GenerateApiAttribute : System.Attribute
{
    /// <summary>
    /// The route prefix for generated endpoints (e.g., ""/api/tvshows"").
    /// If not specified, derived from interface name.
    /// </summary>
    public string? RoutePrefix { get; set; }

    /// <summary>
    /// Fully qualified type name of a static class with a ""Default"" property
    /// returning JsonSerializerOptions (e.g., ""MyApp.MyJsonOptions"").
    /// If not set, a default options instance with camelCase and case-insensitive matching is used.
    /// </summary>
    public string? JsonOptionsType { get; set; }
}
");
        });

        // Find interfaces with [GenerateApi] attribute
        var interfaces = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsInterfaceWithAttribute(node),
                transform: static (ctx, _) => GetRepositoryModel(ctx))
            .Where(static m => m is not null);

        // Collect and generate
        context.RegisterSourceOutput(interfaces.Collect(), static (spc, repositories) =>
        {
            foreach (var repo in repositories)
            {
                if (repo is null) continue;

                spc.AddSource($"IApi{repo.Name}.g.cs", RefitEmitter.Emit(repo));
                spc.AddSource($"Api{repo.Name}Client.g.cs", HttpClientEmitter.Emit(repo));
                spc.AddSource($"Fallback{repo.Name}.g.cs", FallbackEmitter.Emit(repo));
                spc.AddSource($"Combined{repo.Name}.g.cs", CombinedEmitter.Emit(repo));
            }
        });
    }

    private static bool IsInterfaceWithAttribute(SyntaxNode node)
    {
        return node is InterfaceDeclarationSyntax ids &&
               ids.AttributeLists.Count > 0;
    }

    private static RepositoryModel? GetRepositoryModel(GeneratorSyntaxContext context)
    {
        var interfaceSyntax = (InterfaceDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(interfaceSyntax);

        if (symbol is not INamedTypeSymbol interfaceSymbol)
            return null;

        // Check for GenerateApi attribute
        var attribute = interfaceSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "GenerateApiAttribute");

        if (attribute is null)
            return null;

        // Extract route prefix from attribute or derive from name
        var routePrefix = attribute.NamedArguments
            .FirstOrDefault(a => a.Key == "RoutePrefix")
            .Value.Value as string;

        // Extract JsonOptionsType from attribute
        var jsonOptionsType = attribute.NamedArguments
            .FirstOrDefault(a => a.Key == "JsonOptionsType")
            .Value.Value as string;

        var name = interfaceSymbol.Name.StartsWith("I")
            ? interfaceSymbol.Name.Substring(1)
            : interfaceSymbol.Name;

        // Parse all methods
        var methods = interfaceSymbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Select(m => ParseMethod(m))
            .ToList();

        // Detect ID type from method parameters
        var idType = DetectIdType(methods);

        return new RepositoryModel
        {
            Name = name,
            Namespace = interfaceSymbol.ContainingNamespace.ToDisplayString(),
            InterfaceName = interfaceSymbol.Name,
            RoutePrefix = routePrefix ?? DeriveRoutePrefix(name),
            Methods = methods,
            IdType = idType,
            JsonOptionsType = jsonOptionsType
        };
    }

    private static string DetectIdType(List<MethodModel> methods)
    {
        foreach (var method in methods)
        {
            var idParam = method.Parameters.FirstOrDefault(p =>
                p.IsRouteParameter &&
                p.Name.Equals("id", StringComparison.OrdinalIgnoreCase));

            if (idParam != null)
            {
                return idParam.Type;
            }
        }

        return "int";
    }

    private static string DeriveRoutePrefix(string name)
    {
        var routeName = name;
        if (routeName.EndsWith("Repository"))
            routeName = routeName.Substring(0, routeName.Length - "Repository".Length);

        routeName = routeName.ToLowerInvariant();
        if (!routeName.EndsWith("s"))
            routeName += "s";

        return $"/api/{routeName}";
    }

    private static MethodModel ParseMethod(IMethodSymbol method)
    {
        var returnType = method.ReturnType.ToDisplayString();
        var innerType = ExtractInnerType(method.ReturnType);
        var isCollection = IsCollectionType(innerType);
        var isNullable = IsNullableType(innerType);
        var hasSource = HasSourceProperty(method.ReturnType, isCollection);

        var parameters = method.Parameters
            .Select(p => ParseParameter(p, method.Name))
            .ToList();

        return new MethodModel
        {
            Name = method.Name,
            ReturnType = returnType,
            InnerReturnType = innerType,
            ReturnsCollection = isCollection,
            ReturnsNullable = isNullable,
            HasSource = hasSource,
            Parameters = parameters,
            HttpMethod = InferHttpMethod(method.Name, parameters)
        };
    }

    private static ParameterModel ParseParameter(IParameterSymbol param, string methodName)
    {
        var typeName = param.Type.ToDisplayString();
        var isCancellationToken = typeName.Contains("CancellationToken");
        var isPrimitive = IsPrimitiveType(param.Type);

        var isRouteParam = IsRouteParameter(param.Name, methodName);

        var isBodyParam = !isPrimitive && !isCancellationToken && !isRouteParam &&
                          (methodName.StartsWith("Upsert") || methodName.StartsWith("Create") ||
                           methodName.StartsWith("Update") || methodName.StartsWith("Add"));

        return new ParameterModel
        {
            Name = param.Name,
            Type = typeName,
            HasDefaultValue = param.HasExplicitDefaultValue,
            DefaultValue = param.HasExplicitDefaultValue ? param.ExplicitDefaultValue : null,
            IsCancellationToken = isCancellationToken,
            IsRouteParameter = isRouteParam,
            IsQueryParameter = isPrimitive && !isRouteParam && !isCancellationToken,
            IsBodyParameter = isBodyParam
        };
    }

    private static bool IsRouteParameter(string paramName, string methodName)
    {
        if (paramName.Equals("id", StringComparison.OrdinalIgnoreCase))
            return true;

        if (paramName.EndsWith("Id", StringComparison.OrdinalIgnoreCase) &&
            (methodName.StartsWith("Get") || methodName.StartsWith("Delete")))
            return true;

        return false;
    }

    private static Models.HttpMethod InferHttpMethod(string methodName, List<ParameterModel> parameters)
    {
        if (methodName.StartsWith("Get") || methodName.StartsWith("Search") || methodName.StartsWith("Find"))
            return Models.HttpMethod.Get;

        if (methodName.StartsWith("Delete") || methodName.StartsWith("Remove"))
            return Models.HttpMethod.Delete;

        if (methodName.StartsWith("Create") || methodName.StartsWith("Add"))
            return Models.HttpMethod.Post;

        if (methodName.StartsWith("Update"))
            return Models.HttpMethod.Put;

        if (methodName.StartsWith("Upsert"))
        {
            return parameters.Any(p => p.IsBodyParameter) ? Models.HttpMethod.Post : Models.HttpMethod.Put;
        }

        return parameters.Any(p => p.IsBodyParameter) ? Models.HttpMethod.Post : Models.HttpMethod.Get;
    }

    private static string ExtractInnerType(ITypeSymbol returnType)
    {
        var displayString = returnType.ToDisplayString();

        if (displayString == "System.Threading.Tasks.Task" || displayString == "Task")
        {
            return "void";
        }

        if (returnType is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var typeName = namedType.ConstructedFrom.ToDisplayString();
            if (typeName.StartsWith("System.Threading.Tasks.Task<"))
            {
                return namedType.TypeArguments[0].ToDisplayString();
            }
        }

        return displayString;
    }

    private static bool IsCollectionType(string typeName)
    {
        return typeName.StartsWith("System.Collections.Generic.IReadOnlyList<") ||
               typeName.StartsWith("System.Collections.Generic.List<") ||
               typeName.StartsWith("System.Collections.Generic.IEnumerable<") ||
               typeName.StartsWith("System.Collections.Generic.IList<") ||
               typeName.StartsWith("System.Collections.Generic.ICollection<");
    }

    private static bool IsNullableType(string typeName)
    {
        return typeName.EndsWith("?");
    }

    private static bool IsPrimitiveType(ITypeSymbol type)
    {
        var typeName = type.ToDisplayString();

        if (typeName.EndsWith("?"))
            typeName = typeName.Substring(0, typeName.Length - 1);

        return typeName switch
        {
            "int" or "System.Int32" => true,
            "long" or "System.Int64" => true,
            "short" or "System.Int16" => true,
            "byte" or "System.Byte" => true,
            "bool" or "System.Boolean" => true,
            "string" or "System.String" => true,
            "double" or "System.Double" => true,
            "float" or "System.Single" => true,
            "decimal" or "System.Decimal" => true,
            "System.Guid" => true,
            "System.DateTime" => true,
            "System.DateTimeOffset" => true,
            "System.DateOnly" => true,
            "System.TimeOnly" => true,
            "System.TimeSpan" => true,
            _ => false
        };
    }

    private static bool HasSourceProperty(ITypeSymbol returnType, bool isCollection)
    {
        var innerType = GetInnerTypeSymbol(returnType);
        if (innerType == null)
            return false;

        if (innerType.SpecialType == SpecialType.System_Void)
            return false;

        var targetType = innerType;
        if (isCollection && innerType is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            targetType = namedType.TypeArguments.FirstOrDefault() ?? innerType;
        }

        if (targetType is INamedTypeSymbol nullable &&
            nullable.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
        {
            targetType = nullable.TypeArguments.FirstOrDefault() ?? targetType;
        }

        if (targetType.NullableAnnotation == NullableAnnotation.Annotated &&
            targetType.OriginalDefinition is INamedTypeSymbol original)
        {
            targetType = original;
        }

        return targetType.GetMembers("Source")
            .OfType<IPropertySymbol>()
            .Any(p => p.Type.ToDisplayString().Contains("DataSource"));
    }

    private static ITypeSymbol? GetInnerTypeSymbol(ITypeSymbol returnType)
    {
        var displayString = returnType.ToDisplayString();
        if (displayString == "System.Threading.Tasks.Task" || displayString == "Task")
            return null;

        if (returnType is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var typeName = namedType.ConstructedFrom.ToDisplayString();
            if (typeName.StartsWith("System.Threading.Tasks.Task<"))
            {
                return namedType.TypeArguments.FirstOrDefault();
            }
        }

        return returnType;
    }
}
